name: "🐛 Bug反馈"
description: 创建一条关于程序异常的反馈.
title: "🐛 [BUG] - 标题"
labels: [
  "bug"
]
body:
  - type: markdown
    attributes:
      value: |
        感谢对项目的支持与关注。
  - type: checkboxes
    attributes:
      label: 这个问题是否已经存在？
      options:
        - label: 我已经在Issue页面搜索过现有的问题 (https://gitee.com/moonfeather/MaiMap/issues)
          required: true
  - type: textarea
    id: description
    attributes:
      label: "描述"
      description: 请简要描述您使用过程中遇到的问题
      placeholder: 简要描述您使用过程中遇到的问题...
    validations:
      required: true
  - type: input
    id: reprod-url
    attributes:
      label: "错误重现URL"
      description: 您可填写网站发生错误时的URL
      placeholder: 例如. https://maimap.tech/?lat=22.3193039&lng=114.1693611&detailId=9
    validations:
      required: false
  - type: textarea
    id: reprod
    attributes:
      label: "错误重现步骤"
      description: 请填写触发Bug的过程
      value: |
        1. 访问网站
        2. 点击 '....'
        3. 滑动至 '....'
        4. 触发Bug
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: "屏幕截图"
      description: 如果可以的话，添加一张屏幕截图来辅助定位问题
      placeholder: 在上方工具栏中上传图片...
    validations:
      required: false
  - type: textarea
    id: browsers
    attributes:
      label: "浏览器"
      description: 填写您触发Bug时使用的浏览器
      placeholder: 例如. Chrome、Firefox、小米浏览器、夸克浏览器
    validations:
      required: true